version: "3.8"

services:

  accounts:
    image: tellravee/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tellravee-network
    
  loans:
    image: tellravee/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tellravee-network
    
  cards:
    image: tellravee/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tellravee-network
    
networks:
  tellravee-network: